version: '3.7'

networks:
  elixir:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/16

x-elixir-def:
  &elixir-def
  build:
    dockerfile: prod.Dockerfile
    context: .

services:
  elixir-1:
    << : *elixir-def
    hostname: elixir-1.local
    container_name: elixir-1
    healthcheck:
      test: sh /opt/app/check.sh
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      HOSTNAME: 10.50.1.1
    ports:
      - '40001:4000'
    networks:
      elixir:
        ipv4_address: 10.50.1.1
    command: ["/opt/app/_build/prod/rel/excluster/bin/excluster", "foreground"]

  elixir-2:
    << : *elixir-def
    hostname: elixir-2.local
    container_name: elixir-2
    healthcheck:
      test: sh /opt/app/check.sh
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      HOSTNAME: 10.50.1.2
    ports:
      - '40002:4000'
    networks:
      elixir:
        ipv4_address: 10.50.1.2
    tty: true
    # command: ["/bin/bash"]
    command: ["/opt/app/_build/prod/rel/excluster/bin/excluster", "foreground"]

  elixir-3:
    << : *elixir-def
    hostname: elixir-3.local
    
    container_name: elixir-3
    healthcheck:
      test: sh /opt/app/check.sh
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      HOSTNAME: 10.50.1.3
    ports:
      - '40003:4000'
    networks:
      elixir:
        ipv4_address: 10.50.1.3
    tty: true
    command: ["/bin/bash"]
    # command: ["/opt/app/_build/prod/rel/excluster/bin/excluster", "foreground"]