version: '3.7'

networks:
  elixir:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/16

x-elixir-def:
  &elixir-def
  build:
    dockerfile: prod.Dockerfile
    context: .
  command: ["/opt/app/_build/prod/rel/excluster/bin/excluster", "console"]

services:
  elixir-1:
    << : *elixir-def
    hostname: elixir-1
    container_name: elixir-1
    environment:
      HOSTNAME: 10.50.1.1
      FRIEND: 10.50.1.2
    networks:
      elixir:
        ipv4_address: 10.50.1.1

  elixir-2:
    << : *elixir-def
    hostname: elixir-2
    container_name: elixir-2
    environment:
      HOSTNAME: 10.50.1.2
      FRIEND: 10.50.1.1
    networks:
      elixir:
        ipv4_address: 10.50.1.2