version: '3.7'

networks:
  elixir:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/16

x-elixir-def:
  &elixir-def
  build:
    dockerfile: prod.Dockerfile
    context: .

services:
  elixir-1:
    << : *elixir-def
    hostname: elixir-1
    container_name: elixir-1
    environment:
      HOSTNAME: 10.50.1.1
    networks:
      elixir:
        ipv4_address: 10.50.1.1

  elixir-2:
    << : *elixir-def
    hostname: elixir-2
    container_name: elixir-2
    environment:
      HOSTNAME: 10.50.1.2
    networks:
      elixir:
        ipv4_address: 10.50.1.2
        
  elixir-3:
    << : *elixir-def
    hostname: elixir-3
    container_name: elixir-3
    environment:
      HOSTNAME: 10.50.1.3
    networks:
      elixir:
        ipv4_address: 10.50.1.3